Repository graphite-project/carbon, pull requests merged in 2018-08, with the labels that each got.

#790 rewrite is handled in pipeline now
  .travis.yml
  lib/carbon/aggregator/processor.py
  lib/carbon/tests/test_aggregator_processor.py
Labels: proposedfix

#796 aggregator: hide "Allocating new metric"
  lib/carbon/aggregator/buffers.py
Labels: bug

#799 Allow strategies to return None
  lib/carbon/cache.py
Labels: enhancement

#798 carbon.conf.example: add more TCP_KEEPALIVE documentation
  conf/carbon.conf.example
Labels: documentation

#802 Fix compatibility issues
  lib/carbon/client.py
Labels: enhancement

#801 Add DESTINATIONS_POOL_REPLICAS
  conf/carbon.conf.example
  lib/carbon/client.py
  lib/carbon/conf.py
  lib/carbon/instrumentation.py
  lib/carbon/resolver.py
  lib/carbon/routers.py
  lib/carbon/tests/test_routers.py
Labels: enhancement

#800 Stop accept() when we reach MAX_RECEIVER_CONNECTIONS
  lib/carbon/protocols.py
  lib/carbon/state.py
Labels: enhancement
